# Generated by Django 2.2.7 on 2019-12-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_auto_20191207_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='DeviceName')),
                ('IP', models.TextField(default='x.x.x.x')),
                ('Category', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('-', '-')], default='-', max_length=500)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.Projects')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.Sites')),
            ],
        ),
    ]
