# Generated by Django 2.2.7 on 2019-12-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='Name',
            new_name='DeviceName',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='Name',
            new_name='SiteName',
        ),
    ]
