# Generated by Django 2.2.7 on 2019-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_auto_20191213_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='DeviceName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='SiteName',
        ),
        migrations.AddField(
            model_name='sites',
            name='Name',
            field=models.TextField(default='SiteName'),
        ),
    ]
