# Generated by Django 2.2.7 on 2020-01-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_auto_20191213_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='Role',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Backup', 'Backup')], default='-', max_length=500),
        ),
    ]
