# Generated by Django 2.2.7 on 2020-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_devices_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='Role',
        ),
        migrations.AlterField(
            model_name='devices',
            name='Category',
            field=models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Choose category', 'Choose the category')], default='Choose category', max_length=500),
        ),
    ]
