# Generated by Django 2.2.7 on 2020-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_auto_20200121_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='Contact',
            field=models.TextField(default='Contact info'),
        ),
    ]
